all:
  vars:
    ansible_ssh_user: ubuntu
    harbor_admin: cncfdemo
    cert_domain_name: registry.cncf.raj.ninja
    cert_admin_email: matheus@nanoshots.com.br
  children:
    kubernetes:
      children: 
        masters:
          vars:
            linkerd_url: linkerd.raj.ninja
            argo_url: argo.raj.ninja
            argo_grpc: grpc.argo.raj.ninja
          hosts:
            54.89.20.28:
        nodes:
          hosts:
            3.81.86.216:
            54.198.34.238:
            52.90.184.91:
            54.87.59.39: 

    harbor:
      hosts:
        34.71.192.242

    front-proxy:
      hosts:
        54.81.151.29: